name: Publish to nuget

on:
  push:
    branches:
      - main
    paths:
      - src/version.props
      - .github/workflows/nuget.yml

env:
  FRAMEWORK: netcoreapp3.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set tests path
        run: echo "TEST_RESULTS_PATH=${{ github.workspace }}/TestResults/" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Run tests
        run: |
          PROJECTS=(
            './Likvido.ApiAuth.Tests/Likvido.ApiAuth.Tests.csproj')
          printf "%s\n" "${PROJECTS[@]}" | xargs -n1 -I file /bin/bash -c 'dotnet restore file'
          printf "%s\n" "${PROJECTS[@]}" | xargs -n1 -I file /bin/bash -c 'dotnet build file --framework ${{ env.FRAMEWORK }} --no-restore --configuration debug'
          paste <(printf "%s\n" "${!PROJECTS[@]}") <(printf "%s\n" "${PROJECTS[@]}") | xargs -n2 /bin/bash -c 'dotnet test $1 --framework --framework ${{ env.FRAMEWORK }} --no-build --no-restore --configuration debug --logger:"nunit;LogFilePath=${{ env.TEST_RESULTS_PATH }}$0.xml"'
        working-directory: ./src
      - name: Publish NuGet Likvido.ApiAuth.Common
        uses: brandedoutcast/publish-nuget@v2.5.5
        id: publish_nuget_common
        with:
          PROJECT_FILE_PATH: src/Likvido.ApiAuth.Common/Likvido.ApiAuth.Common.csproj
          VERSION_FILE_PATH: src/version.props
          PACKAGE_NAME: Likvido.ApiAuth.Common
          VERSION_REGEX: <Version>(.*)<\/Version>
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
      - name: Extract version
        uses: bhowell2/github-substring-action@v1.0.0
        id: common_version
        with:
          value: ${{steps.publish_nuget_common.outputs.VERSION}}
          index_of_str: "v"
      - name: Wait for common package
        uses: cygnetdigital/wait_for_response@v2.0.0
        with:
            url: "https://api.nuget.org/v3/registration5-semver1/likvido.apiauth.common/${{steps.common_version.outputs.substring}}.json"
            responseCode: "200"
            timeout: 600000
            interval: 30000
      - name: Publish NuGet Likvido.ApiAuth.Client
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: src/Likvido.ApiAuth.Client/Likvido.ApiAuth.Client.csproj
          VERSION_FILE_PATH: src/version.props
          PACKAGE_NAME: Likvido.ApiAuth.Client
          VERSION_REGEX: <Version>(.*)<\/Version>
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          TAG_COMMIT: false
      - name: Publish NuGet Likvido.ApiAuth.Server
        uses: brandedoutcast/publish-nuget@v2.5.5
        with:
          PROJECT_FILE_PATH: src/Likvido.ApiAuth.Server/Likvido.ApiAuth.Server.csproj
          VERSION_FILE_PATH: src/version.props
          PACKAGE_NAME: Likvido.ApiAuth.Server
          VERSION_REGEX: <Version>(.*)<\/Version>
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          TAG_COMMIT: false
